function out1 = get_coeff_coop_n25(in1,in2,in3,~,in5,in6)
%GET_COEFF_COOP_N25
%    OUT1 = GET_COEFF_COOP_N25(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:02:53

A_p1_1 = in1(1);
A_p2_1 = in1(2);
A_p2_3 = in1(8);
A_p3_3 = in1(9);
A_ps2_1 = in3(2);
A_ps2_2 = in3(5);
A_ps2_3 = in3(8);
A_s1_1 = in2(1);
A_s2_2 = in2(5);
A_s3_3 = in2(9);
bp1 = in5(1,:);
bp2 = in5(2,:);
bp3 = in5(3,:);
bs1 = in6(1,:);
bs2 = in6(2,:);
bs3 = in6(3,:);
out1 = A_p1_1.*bp2-A_p2_1.*bp1-A_p2_3.*bp3+A_p3_3.*bp2+A_s1_1.*bp2+A_s2_2.*bp2+A_s3_3.*bp2-A_ps2_1.*bs1-A_ps2_2.*bs2-A_ps2_3.*bs3;
end
