function out1 = get_coeff_coop_d17(~,~,~,~,~,~)
%GET_COEFF_COOP_D17
%    OUT1 = GET_COEFF_COOP_D17(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:04:55

out1 = -1.0;
end
