function out1 = get_coeff_coop_n65(in1,in2,~,in4,in5,in6)
%GET_COEFF_COOP_N65
%    OUT1 = GET_COEFF_COOP_N65(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:50

A_p1_1 = in1(1);
A_p2_2 = in1(5);
A_p3_3 = in1(9);
A_s1_1 = in2(1);
A_s2_2 = in2(5);
A_s3_1 = in2(3);
A_s3_2 = in2(6);
A_sp3_1 = in4(3);
A_sp3_2 = in4(6);
A_sp3_3 = in4(9);
bp1 = in5(1,:);
bp2 = in5(2,:);
bp3 = in5(3,:);
bs1 = in6(1,:);
bs2 = in6(2,:);
bs3 = in6(3,:);
out1 = A_sp3_1.*bp1+A_sp3_2.*bp2+A_sp3_3.*bp3-A_p1_1.*bs3-A_p2_2.*bs3-A_p3_3.*bs3-A_s1_1.*bs3-A_s2_2.*bs3+A_s3_1.*bs1+A_s3_2.*bs2;
end
