function out1 = get_coeff_coop_n26(~,~,~,~,in5,~)
%GET_COEFF_COOP_N26
%    OUT1 = GET_COEFF_COOP_N26(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:02:53

bp2 = in5(2,:);
out1 = bp2;
end
