function out1 = get_coeff_coop_n56(~,~,~,~,~,in6)
%GET_COEFF_COOP_N56
%    OUT1 = GET_COEFF_COOP_N56(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:42

bs2 = in6(2,:);
out1 = -bs2;
end
