function out1 = get_coeff_coop_n46(~,~,~,~,~,in6)
%GET_COEFF_COOP_N46
%    OUT1 = GET_COEFF_COOP_N46(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:36

bs1 = in6(1,:);
out1 = -bs1;
end
