function out1 = get_coeff_coop_n15(in1,in2,in3,in4,in5,in6)
%GET_COEFF_COOP_N15
%    OUT1 = GET_COEFF_COOP_N15(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:02:39

A_p1_2 = in1(4);
A_p1_3 = in1(7);
A_p2_2 = in1(5);
A_p3_3 = in1(9);
A_ps1_1 = in3(1);
A_ps1_2 = in3(4);
A_ps1_3 = in3(7);
A_s1_1 = in2(1);
A_s2_2 = in2(5);
A_s3_3 = in2(9);
bp1 = in5(1,:);
bp2 = in5(2,:);
bp3 = in5(3,:);
bs1 = in6(1,:);
bs2 = in6(2,:);
bs3 = in6(3,:);
out1 = -A_p1_2.*bp2-A_p1_3.*bp3+A_p2_2.*bp1+A_p3_3.*bp1+A_s1_1.*bp1+A_s2_2.*bp1+A_s3_3.*bp1-A_ps1_1.*bs1-A_ps1_2.*bs2-A_ps1_3.*bs3;
end
