function out1 = get_coeff_coop_n45(in1,in2,~,in4,in5,in6)
%GET_COEFF_COOP_N45
%    OUT1 = GET_COEFF_COOP_N45(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:36

A_p1_1 = in1(1);
A_p2_2 = in1(5);
A_p3_3 = in1(9);
A_s1_2 = in2(4);
A_s1_3 = in2(7);
A_s2_2 = in2(5);
A_s3_3 = in2(9);
A_sp1_1 = in4(1);
A_sp1_2 = in4(4);
A_sp1_3 = in4(7);
bp1 = in5(1,:);
bp2 = in5(2,:);
bp3 = in5(3,:);
bs1 = in6(1,:);
bs2 = in6(2,:);
bs3 = in6(3,:);
out1 = A_sp1_1.*bp1+A_sp1_2.*bp2+A_sp1_3.*bp3-A_p1_1.*bs1-A_p2_2.*bs1-A_p3_3.*bs1+A_s1_2.*bs2+A_s1_3.*bs3-A_s2_2.*bs1-A_s3_3.*bs1;
end
