function out1 = get_coeff_coop_d16(in1,in2,~,~,~,~)
%GET_COEFF_COOP_D16
%    OUT1 = GET_COEFF_COOP_D16(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:04:55

A_p1_1 = in1(1);
A_p2_2 = in1(5);
A_p3_3 = in1(9);
A_s1_1 = in2(1);
A_s2_2 = in2(5);
A_s3_3 = in2(9);
out1 = -A_p1_1-A_p2_2-A_p3_3-A_s1_1-A_s2_2-A_s3_3;
end
