function out1 = get_coeff_coop_n36(in1,in2,in3,in4,in5,in6)
%GET_COEFF_COOP_N36
%    OUT1 = GET_COEFF_COOP_N36(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:51:50

bp3 = in5(3,:);
out1 = bp3;
end
