function out1 = get_coeff_coop_n66(~,~,~,~,~,in6)
%GET_COEFF_COOP_N66
%    OUT1 = GET_COEFF_COOP_N66(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:50

bs3 = in6(3,:);
out1 = -bs3;
end
