function out1 = get_coeff_coop_n53(in1,in2,in3,in4,in5,in6)
%GET_COEFF_COOP_N53
%    OUT1 = GET_COEFF_COOP_N53(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-May-2024 02:14:42

A_p1_1 = in1(1);
A_p1_2 = in1(4);
A_p1_3 = in1(7);
A_p2_1 = in1(2);
A_p2_2 = in1(5);
A_p2_3 = in1(8);
A_p3_1 = in1(3);
A_p3_2 = in1(6);
A_p3_3 = in1(9);
A_ps1_1 = in3(1);
A_ps1_3 = in3(7);
A_ps2_1 = in3(2);
A_ps2_3 = in3(8);
A_ps3_1 = in3(3);
A_ps3_3 = in3(9);
A_s1_1 = in2(1);
A_s1_3 = in2(7);
A_s2_1 = in2(2);
A_s2_3 = in2(8);
A_s3_1 = in2(3);
A_s3_3 = in2(9);
A_sp1_1 = in4(1);
A_sp1_2 = in4(4);
A_sp1_3 = in4(7);
A_sp2_1 = in4(2);
A_sp2_2 = in4(5);
A_sp2_3 = in4(8);
A_sp3_1 = in4(3);
A_sp3_2 = in4(6);
A_sp3_3 = in4(9);
bp1 = in5(1,:);
bp2 = in5(2,:);
bp3 = in5(3,:);
bs1 = in6(1,:);
bs2 = in6(2,:);
bs3 = in6(3,:);
et1 = A_p1_1.*A_p2_2.*A_sp2_3.*bp3-A_p1_1.*A_p2_3.*A_sp2_2.*bp3-A_p1_2.*A_p2_1.*A_sp2_3.*bp3+A_p1_2.*A_p2_3.*A_sp2_1.*bp3+A_p1_3.*A_p2_1.*A_sp2_2.*bp3-A_p1_3.*A_p2_2.*A_sp2_1.*bp3-A_p1_1.*A_p3_2.*A_sp2_3.*bp2+A_p1_1.*A_p3_3.*A_sp2_2.*bp2+A_p1_2.*A_p3_1.*A_sp2_3.*bp2-A_p1_2.*A_p3_3.*A_sp2_1.*bp2-A_p1_3.*A_p3_1.*A_sp2_2.*bp2+A_p1_3.*A_p3_2.*A_sp2_1.*bp2+A_p2_1.*A_p3_2.*A_sp2_3.*bp1-A_p2_1.*A_p3_3.*A_sp2_2.*bp1-A_p2_2.*A_p3_1.*A_sp2_3.*bp1+A_p2_2.*A_p3_3.*A_sp2_1.*bp1+A_p2_3.*A_p3_1.*A_sp2_2.*bp1-A_p2_3.*A_p3_2.*A_sp2_1.*bp1+A_p1_1.*A_s1_1.*A_sp2_2.*bp2-A_p1_1.*A_s2_1.*A_sp1_2.*bp2-A_p1_2.*A_s1_1.*A_sp2_1.*bp2+A_p1_2.*A_s2_1.*A_sp1_1.*bp2+A_p1_1.*A_s1_1.*A_sp2_3.*bp3-A_p1_1.*A_s2_1.*A_sp1_3.*bp3-A_p1_3.*A_s1_1.*A_sp2_1.*bp3+A_p1_3.*A_s2_1.*A_sp1_1.*bp3-A_p2_1.*A_s1_1.*A_sp2_2.*bp1+A_p2_1.*A_s2_1.*A_sp1_2.*bp1+A_p2_2.*A_s1_1.*A_sp2_1.*bp1-A_p2_2.*A_s2_1.*A_sp1_1.*bp1+A_p2_2.*A_s1_1.*A_sp2_3.*bp3-A_p2_2.*A_s2_1.*A_sp1_3.*bp3-A_p2_3.*A_s1_1.*A_sp2_2.*bp3;
et2 = A_p2_3.*A_s2_1.*A_sp1_2.*bp3-A_p3_1.*A_s1_1.*A_sp2_3.*bp1+A_p3_1.*A_s2_1.*A_sp1_3.*bp1+A_p3_3.*A_s1_1.*A_sp2_1.*bp1-A_p3_3.*A_s2_1.*A_sp1_1.*bp1-A_p1_1.*A_s2_3.*A_sp3_2.*bp2+A_p1_1.*A_s3_3.*A_sp2_2.*bp2+A_p1_2.*A_s2_3.*A_sp3_1.*bp2-A_p1_2.*A_s3_3.*A_sp2_1.*bp2-A_p3_2.*A_s1_1.*A_sp2_3.*bp2+A_p3_2.*A_s2_1.*A_sp1_3.*bp2+A_p3_3.*A_s1_1.*A_sp2_2.*bp2-A_p3_3.*A_s2_1.*A_sp1_2.*bp2-A_p1_1.*A_s2_3.*A_sp3_3.*bp3+A_p1_1.*A_s3_3.*A_sp2_3.*bp3+A_p1_3.*A_s2_3.*A_sp3_1.*bp3-A_p1_3.*A_s3_3.*A_sp2_1.*bp3+A_p2_1.*A_s2_3.*A_sp3_2.*bp1-A_p2_1.*A_s3_3.*A_sp2_2.*bp1-A_p2_2.*A_s2_3.*A_sp3_1.*bp1+A_p2_2.*A_s3_3.*A_sp2_1.*bp1-A_p2_2.*A_s2_3.*A_sp3_3.*bp3+A_p2_2.*A_s3_3.*A_sp2_3.*bp3+A_p2_3.*A_s2_3.*A_sp3_2.*bp3-A_p2_3.*A_s3_3.*A_sp2_2.*bp3+A_p3_1.*A_s2_3.*A_sp3_3.*bp1-A_p3_1.*A_s3_3.*A_sp2_3.*bp1-A_p3_3.*A_s2_3.*A_sp3_1.*bp1+A_p3_3.*A_s3_3.*A_sp2_1.*bp1+A_p3_2.*A_s2_3.*A_sp3_3.*bp2-A_p3_2.*A_s3_3.*A_sp2_3.*bp2-A_p3_3.*A_s2_3.*A_sp3_2.*bp2+A_p3_3.*A_s3_3.*A_sp2_2.*bp2;
et3 = -A_ps1_1.*A_sp1_1.*A_sp2_2.*bp2+A_ps1_1.*A_sp1_2.*A_sp2_1.*bp2-A_ps1_1.*A_sp1_1.*A_sp2_3.*bp3+A_ps1_1.*A_sp1_3.*A_sp2_1.*bp3+A_ps2_1.*A_sp1_1.*A_sp2_2.*bp1-A_ps2_1.*A_sp1_2.*A_sp2_1.*bp1-A_ps2_1.*A_sp1_2.*A_sp2_3.*bp3+A_ps2_1.*A_sp1_3.*A_sp2_2.*bp3+A_ps3_1.*A_sp1_1.*A_sp2_3.*bp1-A_ps3_1.*A_sp1_3.*A_sp2_1.*bp1+A_ps1_3.*A_sp2_1.*A_sp3_2.*bp2-A_ps1_3.*A_sp2_2.*A_sp3_1.*bp2+A_ps3_1.*A_sp1_2.*A_sp2_3.*bp2-A_ps3_1.*A_sp1_3.*A_sp2_2.*bp2+A_ps1_3.*A_sp2_1.*A_sp3_3.*bp3-A_ps1_3.*A_sp2_3.*A_sp3_1.*bp3-A_ps2_3.*A_sp2_1.*A_sp3_2.*bp1+A_ps2_3.*A_sp2_2.*A_sp3_1.*bp1+A_ps2_3.*A_sp2_2.*A_sp3_3.*bp3-A_ps2_3.*A_sp2_3.*A_sp3_2.*bp3-A_ps3_3.*A_sp2_1.*A_sp3_3.*bp1+A_ps3_3.*A_sp2_3.*A_sp3_1.*bp1-A_ps3_3.*A_sp2_2.*A_sp3_3.*bp2+A_ps3_3.*A_sp2_3.*A_sp3_2.*bp2-A_s1_1.*A_s2_3.*A_sp3_1.*bp1+A_s1_1.*A_s3_3.*A_sp2_1.*bp1+A_s1_3.*A_s2_1.*A_sp3_1.*bp1-A_s1_3.*A_s3_1.*A_sp2_1.*bp1-A_s2_1.*A_s3_3.*A_sp1_1.*bp1+A_s2_3.*A_s3_1.*A_sp1_1.*bp1-A_s1_1.*A_s2_3.*A_sp3_2.*bp2+A_s1_1.*A_s3_3.*A_sp2_2.*bp2+A_s1_3.*A_s2_1.*A_sp3_2.*bp2;
et4 = -A_s1_3.*A_s3_1.*A_sp2_2.*bp2-A_s2_1.*A_s3_3.*A_sp1_2.*bp2+A_s2_3.*A_s3_1.*A_sp1_2.*bp2-A_s1_1.*A_s2_3.*A_sp3_3.*bp3+A_s1_1.*A_s3_3.*A_sp2_3.*bp3+A_s1_3.*A_s2_1.*A_sp3_3.*bp3-A_s1_3.*A_s3_1.*A_sp2_3.*bp3-A_s2_1.*A_s3_3.*A_sp1_3.*bp3+A_s2_3.*A_s3_1.*A_sp1_3.*bp3-A_p1_1.*A_p2_2.*A_p3_3.*bs2+A_p1_1.*A_p2_3.*A_p3_2.*bs2+A_p1_2.*A_p2_1.*A_p3_3.*bs2-A_p1_2.*A_p2_3.*A_p3_1.*bs2-A_p1_3.*A_p2_1.*A_p3_2.*bs2+A_p1_3.*A_p2_2.*A_p3_1.*bs2-A_p1_1.*A_p2_2.*A_s1_1.*bs2+A_p1_2.*A_p2_1.*A_s1_1.*bs2+A_p1_1.*A_p2_2.*A_s2_1.*bs1-A_p1_2.*A_p2_1.*A_s2_1.*bs1-A_p1_1.*A_p3_3.*A_s1_1.*bs2+A_p1_3.*A_p3_1.*A_s1_1.*bs2+A_p1_1.*A_p2_2.*A_s2_3.*bs3-A_p1_2.*A_p2_1.*A_s2_3.*bs3+A_p1_1.*A_p3_3.*A_s2_1.*bs1-A_p1_3.*A_p3_1.*A_s2_1.*bs1-A_p1_1.*A_p2_2.*A_s3_3.*bs2+A_p1_2.*A_p2_1.*A_s3_3.*bs2-A_p2_2.*A_p3_3.*A_s1_1.*bs2+A_p2_3.*A_p3_2.*A_s1_1.*bs2+A_p1_1.*A_p3_3.*A_s2_3.*bs3-A_p1_3.*A_p3_1.*A_s2_3.*bs3+A_p2_2.*A_p3_3.*A_s2_1.*bs1-A_p2_3.*A_p3_2.*A_s2_1.*bs1;
et5 = -A_p1_1.*A_p3_3.*A_s3_3.*bs2+A_p1_3.*A_p3_1.*A_s3_3.*bs2+A_p2_2.*A_p3_3.*A_s2_3.*bs3-A_p2_3.*A_p3_2.*A_s2_3.*bs3-A_p2_2.*A_p3_3.*A_s3_3.*bs2+A_p2_3.*A_p3_2.*A_s3_3.*bs2+A_p1_1.*A_ps2_1.*A_sp1_2.*bs2-A_p1_2.*A_ps2_1.*A_sp1_1.*bs2-A_p2_1.*A_ps1_1.*A_sp1_2.*bs2+A_p2_2.*A_ps1_1.*A_sp1_1.*bs2-A_p1_1.*A_ps2_1.*A_sp2_2.*bs1+A_p1_2.*A_ps2_1.*A_sp2_1.*bs1+A_p2_1.*A_ps1_1.*A_sp2_2.*bs1-A_p2_2.*A_ps1_1.*A_sp2_1.*bs1+A_p1_1.*A_ps3_1.*A_sp1_3.*bs2-A_p1_3.*A_ps3_1.*A_sp1_1.*bs2-A_p3_1.*A_ps1_1.*A_sp1_3.*bs2+A_p3_3.*A_ps1_1.*A_sp1_1.*bs2-A_p1_1.*A_ps2_3.*A_sp2_2.*bs3+A_p1_2.*A_ps2_3.*A_sp2_1.*bs3+A_p2_1.*A_ps1_3.*A_sp2_2.*bs3-A_p2_2.*A_ps1_3.*A_sp2_1.*bs3-A_p1_1.*A_ps3_1.*A_sp2_3.*bs1+A_p1_3.*A_ps3_1.*A_sp2_1.*bs1+A_p3_1.*A_ps1_1.*A_sp2_3.*bs1-A_p3_3.*A_ps1_1.*A_sp2_1.*bs1+A_p1_1.*A_ps2_3.*A_sp3_2.*bs2-A_p1_2.*A_ps2_3.*A_sp3_1.*bs2-A_p2_1.*A_ps1_3.*A_sp3_2.*bs2+A_p2_2.*A_ps1_3.*A_sp3_1.*bs2+A_p2_2.*A_ps3_1.*A_sp1_3.*bs2-A_p2_3.*A_ps3_1.*A_sp1_2.*bs2-A_p3_2.*A_ps2_1.*A_sp1_3.*bs2;
et6 = A_p3_3.*A_ps2_1.*A_sp1_2.*bs2-A_p1_1.*A_ps3_3.*A_sp2_3.*bs3+A_p1_3.*A_ps3_3.*A_sp2_1.*bs3+A_p3_1.*A_ps1_3.*A_sp2_3.*bs3-A_p3_3.*A_ps1_3.*A_sp2_1.*bs3-A_p2_2.*A_ps3_1.*A_sp2_3.*bs1+A_p2_3.*A_ps3_1.*A_sp2_2.*bs1+A_p3_2.*A_ps2_1.*A_sp2_3.*bs1-A_p3_3.*A_ps2_1.*A_sp2_2.*bs1+A_p1_1.*A_ps3_3.*A_sp3_3.*bs2-A_p1_3.*A_ps3_3.*A_sp3_1.*bs2-A_p3_1.*A_ps1_3.*A_sp3_3.*bs2+A_p3_3.*A_ps1_3.*A_sp3_1.*bs2-A_p2_2.*A_ps3_3.*A_sp2_3.*bs3+A_p2_3.*A_ps3_3.*A_sp2_2.*bs3+A_p3_2.*A_ps2_3.*A_sp2_3.*bs3-A_p3_3.*A_ps2_3.*A_sp2_2.*bs3+A_p2_2.*A_ps3_3.*A_sp3_3.*bs2-A_p2_3.*A_ps3_3.*A_sp3_2.*bs2-A_p3_2.*A_ps2_3.*A_sp3_3.*bs2+A_p3_3.*A_ps2_3.*A_sp3_2.*bs2+A_p1_1.*A_s1_1.*A_s2_3.*bs3-A_p1_1.*A_s1_3.*A_s2_1.*bs3-A_p1_1.*A_s1_1.*A_s3_3.*bs2+A_p1_1.*A_s1_3.*A_s3_1.*bs2+A_p2_2.*A_s1_1.*A_s2_3.*bs3-A_p2_2.*A_s1_3.*A_s2_1.*bs3+A_p1_1.*A_s2_1.*A_s3_3.*bs1-A_p1_1.*A_s2_3.*A_s3_1.*bs1-A_p2_2.*A_s1_1.*A_s3_3.*bs2+A_p2_2.*A_s1_3.*A_s3_1.*bs2+A_p3_3.*A_s1_1.*A_s2_3.*bs3-A_p3_3.*A_s1_3.*A_s2_1.*bs3;
et7 = A_p2_2.*A_s2_1.*A_s3_3.*bs1-A_p2_2.*A_s2_3.*A_s3_1.*bs1-A_p3_3.*A_s1_1.*A_s3_3.*bs2+A_p3_3.*A_s1_3.*A_s3_1.*bs2+A_p3_3.*A_s2_1.*A_s3_3.*bs1-A_p3_3.*A_s2_3.*A_s3_1.*bs1+A_ps1_1.*A_s1_3.*A_sp2_1.*bs3-A_ps1_1.*A_s2_3.*A_sp1_1.*bs3-A_ps1_3.*A_s1_1.*A_sp2_1.*bs3+A_ps1_3.*A_s2_1.*A_sp1_1.*bs3-A_ps1_1.*A_s1_3.*A_sp3_1.*bs2+A_ps1_1.*A_s3_3.*A_sp1_1.*bs2+A_ps1_3.*A_s1_1.*A_sp3_1.*bs2-A_ps1_3.*A_s3_1.*A_sp1_1.*bs2+A_ps2_1.*A_s1_3.*A_sp2_2.*bs3-A_ps2_1.*A_s2_3.*A_sp1_2.*bs3-A_ps2_3.*A_s1_1.*A_sp2_2.*bs3+A_ps2_3.*A_s2_1.*A_sp1_2.*bs3+A_ps1_1.*A_s2_3.*A_sp3_1.*bs1-A_ps1_1.*A_s3_3.*A_sp2_1.*bs1-A_ps1_3.*A_s2_1.*A_sp3_1.*bs1+A_ps1_3.*A_s3_1.*A_sp2_1.*bs1-A_ps2_1.*A_s1_3.*A_sp3_2.*bs2+A_ps2_1.*A_s3_3.*A_sp1_2.*bs2+A_ps2_3.*A_s1_1.*A_sp3_2.*bs2-A_ps2_3.*A_s3_1.*A_sp1_2.*bs2+A_ps3_1.*A_s1_3.*A_sp2_3.*bs3-A_ps3_1.*A_s2_3.*A_sp1_3.*bs3-A_ps3_3.*A_s1_1.*A_sp2_3.*bs3+A_ps3_3.*A_s2_1.*A_sp1_3.*bs3+A_ps2_1.*A_s2_3.*A_sp3_2.*bs1-A_ps2_1.*A_s3_3.*A_sp2_2.*bs1-A_ps2_3.*A_s2_1.*A_sp3_2.*bs1;
et8 = A_ps2_3.*A_s3_1.*A_sp2_2.*bs1-A_ps3_1.*A_s1_3.*A_sp3_3.*bs2+A_ps3_1.*A_s3_3.*A_sp1_3.*bs2+A_ps3_3.*A_s1_1.*A_sp3_3.*bs2-A_ps3_3.*A_s3_1.*A_sp1_3.*bs2+A_ps3_1.*A_s2_3.*A_sp3_3.*bs1-A_ps3_1.*A_s3_3.*A_sp2_3.*bs1-A_ps3_3.*A_s2_1.*A_sp3_3.*bs1+A_ps3_3.*A_s3_1.*A_sp2_3.*bs1;
out1 = et1+et2+et3+et4+et5+et6+et7+et8;
end
